[alembic]
# Path to migration scripts
script_location = alembic
# Template used to generate new revision files
revision_script_template = %(scriptdir)s/script.py.mako
# Encoding used when writing/reading values to/from the environment.
encoding = utf-8

# Use a relative path for the env.py file
# Ensure alembic is initialized with `-t async` for async template
file_template = %%(rev)s_%%(head)s_%%(branch)s_%%(slug)s

# The SQLAlchemy URL to connect to the database.
# This value will be overridden by the config.py settings in env.py
# Set a dummy value here for alembic's initial parsing.
sqlalchemy.url = postgresql+asyncpg://user:password@localhost:5432/petstore_alembic_dummy

# Logging configuration
[loggers]
keys = root, sqlalchemy, alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S